In [18]:
#### Numpy
import numpy as np
data1 = [1,5,2,6,5,8,5,6]
arr1 = np.array(data1)
arr1

array([1, 5, 2, 6, 5, 8, 5, 6])

In [15]:
data2 = [[1,5,6,9,8,5],[5,2,6,5,2,5]]
arr2 = np.array(data2)
arr2

array([[1, 5, 6, 9, 8, 5],
       [5, 2, 6, 5, 2, 5]])

In [20]:
### checking the dimensions
arr2.ndim

2

In [21]:
### checking the shappe
arr2.shape

(2, 6)

In [22]:
### array type
arr2.dtype

dtype('int32')

In [25]:
### Creating a 1D array
arr_0_1d =  np.zeros(10)
arr_0_1d

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [24]:
### Creating an multidimemsional array with zeros-- have to pass a tuple
arr0 = np.zeros((5,3))
arr0

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [26]:
### Creating a multidimensional array 2 (3,2) arrays--empty
arr_empty = np.empty((2,3,2))
arr_empty

array([[[ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.]],

       [[ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.]]])

In [28]:
### Generating a sequence in ndarray format 
arr_seq = np.arange(15)
arr_seq

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [32]:
### Creating one's
arr_ones = np.ones((5,2))
arr_ones

array([[ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.]])

In [2]:
### Creating an identity matrix
from  numpy import eye
arr_identity = eye((5))
arr_identity


array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [4]:
#### another way to  cr
import numpy as np
arr_ident = np.identity((5))
arr_ident

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [5]:
### Data type for ndarrays
arr4 = np.array([[1,2,6,9,5,8],[5,9,8,6,5,6]],dtype=np.float)
arr4

array([[ 1.,  2.,  6.,  9.,  5.,  8.],
       [ 5.,  9.,  8.,  6.,  5.,  6.]])

In [7]:
arr5 = np.array([[1,2,6,9,5,8],[5,9,8,6,5,6]],dtype=np.int)
arr5

array([[1, 2, 6, 9, 5, 8],
       [5, 9, 8, 6, 5, 6]])

In [8]:
### Converting the data type of an array 
arr6 = arr5.astype(np.float)
arr6

array([[ 1.,  2.,  6.,  9.,  5.,  8.],
       [ 5.,  9.,  8.,  6.,  5.,  6.]])

In [11]:
### Converting into strings'
arr8= np.array([[1,2,6,9,5,8],[5,9,8,6,5,6]],dtype=np.string_)
arr8

array([[b'1', b'2', b'6', b'9', b'5', b'8'],
       [b'5', b'9', b'8', b'6', b'5', b'6']], 
      dtype='|S1')

In [12]:
### Array slicing 
arr9 = np.array([[1,2,3,6],[5,6,8,9],[8,7,9,5]])
arr9[0]

array([1, 2, 3, 6])

In [14]:
arr9[2]

array([8, 7, 9, 5])

In [16]:
arr9[0][2]

3

In [17]:
arr9[0,2]

3

In [21]:
### Creating a random nummber
arr_random = np.random.randn(7,4)
arr_random

array([[-1.42321135, -0.81027381,  1.15966664,  0.08741861],
       [ 0.15507668, -0.1095223 ,  1.2009298 , -0.30742427],
       [-2.4138597 ,  0.09084879, -1.0429451 ,  0.43215943],
       [ 0.95602001, -0.58116595,  0.49488086,  2.00892965],
       [-0.56797457,  1.12220242, -0.49353098,  0.24540072],
       [-0.79133787, -0.04024351, -0.38149207,  0.24413382],
       [ 0.81099583, -1.43235138,  0.32565912, -1.25419891]])

In [24]:
### Fancy indexing 
arr_empty= np.empty((5,5))
arr_empty

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [28]:
for i in range(5):
    arr_empty[i] = i
    
arr_empty

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.,  4.]])

In [31]:
### indexing the 1st and 3 rd rows
arr_empty[[0,2]]

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 2.,  2.,  2.,  2.,  2.]])

In [33]:
arr_empty[[-3,-4]]

array([[ 2.,  2.,  2.,  2.,  2.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [36]:
### Constructing an array using reshape
arr_reshape = np.arange(32).reshape((8,4))
arr_reshape

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [37]:
arr_reshape[[1,2,3],[2,0,1]]

array([ 6,  8, 13])

In [39]:
### Transposing array
arr_reshape_trans = arr_rehsape.T
arr_reshape_trans

array([[ 0,  4,  8, 12, 16, 20, 24, 28],
       [ 1,  5,  9, 13, 17, 21, 25, 29],
       [ 2,  6, 10, 14, 18, 22, 26, 30],
       [ 3,  7, 11, 15, 19, 23, 27, 31]])

In [42]:
### Data Processing using arrays
arr_dp = np.arange(-5,5,0.1)
xs,xy =np.meshgrid(arr_dp,arr_dp)
xs,xy

(array([[-5. , -4.9, -4.8, ...,  4.7,  4.8,  4.9],
        [-5. , -4.9, -4.8, ...,  4.7,  4.8,  4.9],
        [-5. , -4.9, -4.8, ...,  4.7,  4.8,  4.9],
        ..., 
        [-5. , -4.9, -4.8, ...,  4.7,  4.8,  4.9],
        [-5. , -4.9, -4.8, ...,  4.7,  4.8,  4.9],
        [-5. , -4.9, -4.8, ...,  4.7,  4.8,  4.9]]),
 array([[-5. , -5. , -5. , ..., -5. , -5. , -5. ],
        [-4.9, -4.9, -4.9, ..., -4.9, -4.9, -4.9],
        [-4.8, -4.8, -4.8, ..., -4.8, -4.8, -4.8],
        ..., 
        [ 4.7,  4.7,  4.7, ...,  4.7,  4.7,  4.7],
        [ 4.8,  4.8,  4.8, ...,  4.8,  4.8,  4.8],
        [ 4.9,  4.9,  4.9, ...,  4.9,  4.9,  4.9]]))

In [44]:
### File input and output with arrays
arr10 = np.arange(10)
np.save('Some_array',arr10)

In [45]:
np.load('Some_array.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
### Generating a random number
arr_random_num = np.random.normal(size=(4,4))
arr_random_num

array([[ 0.35195942, -1.69701038, -0.89320014,  1.82717199],
       [ 0.65925442,  2.03824129, -0.2170924 , -0.16479906],
       [ 0.86176558, -0.22958494,  1.4388343 , -0.57417736],
       [ 0.97590891, -0.16256876,  1.69980065, -0.50945865]])